### ISSUE TITLE
Web application error when attempting to run CLIP-Count web app

### ISSUE THREAD

**Issue by BradNeuberg** [songrise/CLIP-Count#9]
I've followed the instructions to install the CLIP-Count web app. I am using Debian GNU/Linux 10 (buster).

First, the default version of gradio installed throws an error on the server side:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/gradio/routes.py", line 282, in api_info
    return gradio.blocks.get_api_info(config, serialize)  # type: ignore
  File "/opt/conda/envs/clipcount/lib/python3.8/site-packages/gradio/blocks.py", line 555, in get_api_info
    serializer = serializing.COMPONENT_MAPPING[type]()
KeyError: 'interpretation'
```

This is solved by downgrading gradio as follows:

pip uninstall gradio -y
pip install gradio==3.26.0

The server and web UI now show up. However, when I then try to use one of the examples from the datasets you trained and evaluated on, I get a client-side error:

![image](https://github.com/songrise/CLIP-Count/assets/148433/d886286e-769c-4d59-827b-ac88ebf2a104)

![image](https://github.com/songrise/CLIP-Count/assets/148433/6e72c0a2-af43-4b33-8a23-41f5f51b2180)

![image](https://github.com/songrise/CLIP-Count/assets/148433/026bb7cc-8864-44c6-b3bc-e6c5dd7a0bf7)

It looks like some kind of 422 Unprocessable Entity is thrown attempting to talk to the server. I see no error logs on the server.

**Comment by BradNeuberg** [comment]
FYI this is fixed by dropping back to an older version of FastAPI:
pip install fastapi==0.99.0

Relevant bug report: https://discuss.huggingface.co/t/fastapi-0-100-0-breaks-gradio/46104
